// Comprehensive list of country calling codes with flags for phone input

export interface CountryCode {
  code: string;
  flag: string;
  country: string;
  label: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: "+93", flag: "🇦🇫", country: "AF", label: "Afeganistão" },
  { code: "+355", flag: "🇦🇱", country: "AL", label: "Albânia" },
  { code: "+213", flag: "🇩🇿", country: "DZ", label: "Argélia" },
  { code: "+376", flag: "🇦🇩", country: "AD", label: "Andorra" },
  { code: "+244", flag: "🇦🇴", country: "AO", label: "Angola" },
  { code: "+54", flag: "🇦🇷", country: "AR", label: "Argentina" },
  { code: "+374", flag: "🇦🇲", country: "AM", label: "Armênia" },
  { code: "+61", flag: "🇦🇺", country: "AU", label: "Austrália" },
  { code: "+43", flag: "🇦🇹", country: "AT", label: "Áustria" },
  { code: "+994", flag: "🇦🇿", country: "AZ", label: "Azerbaijão" },
  { code: "+973", flag: "🇧🇭", country: "BH", label: "Bahrein" },
  { code: "+880", flag: "🇧🇩", country: "BD", label: "Bangladesh" },
  { code: "+375", flag: "🇧🇾", country: "BY", label: "Belarus" },
  { code: "+32", flag: "🇧🇪", country: "BE", label: "Bélgica" },
  { code: "+501", flag: "🇧🇿", country: "BZ", label: "Belize" },
  { code: "+229", flag: "🇧🇯", country: "BJ", label: "Benin" },
  { code: "+975", flag: "🇧🇹", country: "BT", label: "Butão" },
  { code: "+591", flag: "🇧🇴", country: "BO", label: "Bolívia" },
  { code: "+387", flag: "🇧🇦", country: "BA", label: "Bósnia" },
  { code: "+267", flag: "🇧🇼", country: "BW", label: "Botsuana" },
  { code: "+55", flag: "🇧🇷", country: "BR", label: "Brasil" },
  { code: "+673", flag: "🇧🇳", country: "BN", label: "Brunei" },
  { code: "+359", flag: "🇧🇬", country: "BG", label: "Bulgária" },
  { code: "+226", flag: "🇧🇫", country: "BF", label: "Burkina Faso" },
  { code: "+257", flag: "🇧🇮", country: "BI", label: "Burundi" },
  { code: "+855", flag: "🇰🇭", country: "KH", label: "Camboja" },
  { code: "+237", flag: "🇨🇲", country: "CM", label: "Camarões" },
  { code: "+1", flag: "🇨🇦", country: "CA", label: "Canadá" },
  { code: "+238", flag: "🇨🇻", country: "CV", label: "Cabo Verde" },
  { code: "+236", flag: "🇨🇫", country: "CF", label: "Rep. Centro-Africana" },
  { code: "+235", flag: "🇹🇩", country: "TD", label: "Chade" },
  { code: "+56", flag: "🇨🇱", country: "CL", label: "Chile" },
  { code: "+86", flag: "🇨🇳", country: "CN", label: "China" },
  { code: "+57", flag: "🇨🇴", country: "CO", label: "Colômbia" },
  { code: "+269", flag: "🇰🇲", country: "KM", label: "Comores" },
  { code: "+243", flag: "🇨🇩", country: "CD", label: "Congo (RDC)" },
  { code: "+242", flag: "🇨🇬", country: "CG", label: "Congo" },
  { code: "+506", flag: "🇨🇷", country: "CR", label: "Costa Rica" },
  { code: "+385", flag: "🇭🇷", country: "HR", label: "Croácia" },
  { code: "+53", flag: "🇨🇺", country: "CU", label: "Cuba" },
  { code: "+357", flag: "🇨🇾", country: "CY", label: "Chipre" },
  { code: "+420", flag: "🇨🇿", country: "CZ", label: "Tchéquia" },
  { code: "+45", flag: "🇩🇰", country: "DK", label: "Dinamarca" },
  { code: "+253", flag: "🇩🇯", country: "DJ", label: "Djibuti" },
  { code: "+593", flag: "🇪🇨", country: "EC", label: "Equador" },
  { code: "+20", flag: "🇪🇬", country: "EG", label: "Egito" },
  { code: "+503", flag: "🇸🇻", country: "SV", label: "El Salvador" },
  { code: "+240", flag: "🇬🇶", country: "GQ", label: "Guiné Equatorial" },
  { code: "+291", flag: "🇪🇷", country: "ER", label: "Eritreia" },
  { code: "+372", flag: "🇪🇪", country: "EE", label: "Estônia" },
  { code: "+251", flag: "🇪🇹", country: "ET", label: "Etiópia" },
  { code: "+358", flag: "🇫🇮", country: "FI", label: "Finlândia" },
  { code: "+33", flag: "🇫🇷", country: "FR", label: "França" },
  { code: "+241", flag: "🇬🇦", country: "GA", label: "Gabão" },
  { code: "+220", flag: "🇬🇲", country: "GM", label: "Gâmbia" },
  { code: "+995", flag: "🇬🇪", country: "GE", label: "Geórgia" },
  { code: "+49", flag: "🇩🇪", country: "DE", label: "Alemanha" },
  { code: "+233", flag: "🇬🇭", country: "GH", label: "Gana" },
  { code: "+30", flag: "🇬🇷", country: "GR", label: "Grécia" },
  { code: "+502", flag: "🇬🇹", country: "GT", label: "Guatemala" },
  { code: "+224", flag: "🇬🇳", country: "GN", label: "Guiné" },
  { code: "+245", flag: "🇬🇼", country: "GW", label: "Guiné-Bissau" },
  { code: "+592", flag: "🇬🇾", country: "GY", label: "Guiana" },
  { code: "+509", flag: "🇭🇹", country: "HT", label: "Haiti" },
  { code: "+504", flag: "🇭🇳", country: "HN", label: "Honduras" },
  { code: "+852", flag: "🇭🇰", country: "HK", label: "Hong Kong" },
  { code: "+36", flag: "🇭🇺", country: "HU", label: "Hungria" },
  { code: "+354", flag: "🇮🇸", country: "IS", label: "Islândia" },
  { code: "+91", flag: "🇮🇳", country: "IN", label: "Índia" },
  { code: "+62", flag: "🇮🇩", country: "ID", label: "Indonésia" },
  { code: "+98", flag: "🇮🇷", country: "IR", label: "Irã" },
  { code: "+964", flag: "🇮🇶", country: "IQ", label: "Iraque" },
  { code: "+353", flag: "🇮🇪", country: "IE", label: "Irlanda" },
  { code: "+972", flag: "🇮🇱", country: "IL", label: "Israel" },
  { code: "+39", flag: "🇮🇹", country: "IT", label: "Itália" },
  { code: "+225", flag: "🇨🇮", country: "CI", label: "Costa do Marfim" },
  { code: "+876", flag: "🇯🇲", country: "JM", label: "Jamaica" },
  { code: "+81", flag: "🇯🇵", country: "JP", label: "Japão" },
  { code: "+962", flag: "🇯🇴", country: "JO", label: "Jordânia" },
  { code: "+7", flag: "🇰🇿", country: "KZ", label: "Cazaquistão" },
  { code: "+254", flag: "🇰🇪", country: "KE", label: "Quênia" },
  { code: "+965", flag: "🇰🇼", country: "KW", label: "Kuwait" },
  { code: "+996", flag: "🇰🇬", country: "KG", label: "Quirguistão" },
  { code: "+856", flag: "🇱🇦", country: "LA", label: "Laos" },
  { code: "+371", flag: "🇱🇻", country: "LV", label: "Letônia" },
  { code: "+961", flag: "🇱🇧", country: "LB", label: "Líbano" },
  { code: "+231", flag: "🇱🇷", country: "LR", label: "Libéria" },
  { code: "+218", flag: "🇱🇾", country: "LY", label: "Líbia" },
  { code: "+423", flag: "🇱🇮", country: "LI", label: "Liechtenstein" },
  { code: "+370", flag: "🇱🇹", country: "LT", label: "Lituânia" },
  { code: "+352", flag: "🇱🇺", country: "LU", label: "Luxemburgo" },
  { code: "+853", flag: "🇲🇴", country: "MO", label: "Macau" },
  { code: "+261", flag: "🇲🇬", country: "MG", label: "Madagascar" },
  { code: "+265", flag: "🇲🇼", country: "MW", label: "Maláui" },
  { code: "+60", flag: "🇲🇾", country: "MY", label: "Malásia" },
  { code: "+960", flag: "🇲🇻", country: "MV", label: "Maldivas" },
  { code: "+223", flag: "🇲🇱", country: "ML", label: "Mali" },
  { code: "+356", flag: "🇲🇹", country: "MT", label: "Malta" },
  { code: "+222", flag: "🇲🇷", country: "MR", label: "Mauritânia" },
  { code: "+230", flag: "🇲🇺", country: "MU", label: "Maurício" },
  { code: "+52", flag: "🇲🇽", country: "MX", label: "México" },
  { code: "+373", flag: "🇲🇩", country: "MD", label: "Moldávia" },
  { code: "+377", flag: "🇲🇨", country: "MC", label: "Mônaco" },
  { code: "+976", flag: "🇲🇳", country: "MN", label: "Mongólia" },
  { code: "+382", flag: "🇲🇪", country: "ME", label: "Montenegro" },
  { code: "+212", flag: "🇲🇦", country: "MA", label: "Marrocos" },
  { code: "+258", flag: "🇲🇿", country: "MZ", label: "Moçambique" },
  { code: "+95", flag: "🇲🇲", country: "MM", label: "Myanmar" },
  { code: "+264", flag: "🇳🇦", country: "NA", label: "Namíbia" },
  { code: "+977", flag: "🇳🇵", country: "NP", label: "Nepal" },
  { code: "+31", flag: "🇳🇱", country: "NL", label: "Países Baixos" },
  { code: "+64", flag: "🇳🇿", country: "NZ", label: "Nova Zelândia" },
  { code: "+505", flag: "🇳🇮", country: "NI", label: "Nicarágua" },
  { code: "+227", flag: "🇳🇪", country: "NE", label: "Níger" },
  { code: "+234", flag: "🇳🇬", country: "NG", label: "Nigéria" },
  { code: "+850", flag: "🇰🇵", country: "KP", label: "Coreia do Norte" },
  { code: "+389", flag: "🇲🇰", country: "MK", label: "Macedônia do Norte" },
  { code: "+47", flag: "🇳🇴", country: "NO", label: "Noruega" },
  { code: "+968", flag: "🇴🇲", country: "OM", label: "Omã" },
  { code: "+92", flag: "🇵🇰", country: "PK", label: "Paquistão" },
  { code: "+507", flag: "🇵🇦", country: "PA", label: "Panamá" },
  { code: "+675", flag: "🇵🇬", country: "PG", label: "Papua-Nova Guiné" },
  { code: "+595", flag: "🇵🇾", country: "PY", label: "Paraguai" },
  { code: "+51", flag: "🇵🇪", country: "PE", label: "Peru" },
  { code: "+63", flag: "🇵🇭", country: "PH", label: "Filipinas" },
  { code: "+48", flag: "🇵🇱", country: "PL", label: "Polônia" },
  { code: "+351", flag: "🇵🇹", country: "PT", label: "Portugal" },
  { code: "+974", flag: "🇶🇦", country: "QA", label: "Catar" },
  { code: "+40", flag: "🇷🇴", country: "RO", label: "Romênia" },
  { code: "+7", flag: "🇷🇺", country: "RU", label: "Rússia" },
  { code: "+250", flag: "🇷🇼", country: "RW", label: "Ruanda" },
  { code: "+966", flag: "🇸🇦", country: "SA", label: "Arábia Saudita" },
  { code: "+221", flag: "🇸🇳", country: "SN", label: "Senegal" },
  { code: "+381", flag: "🇷🇸", country: "RS", label: "Sérvia" },
  { code: "+65", flag: "🇸🇬", country: "SG", label: "Singapura" },
  { code: "+421", flag: "🇸🇰", country: "SK", label: "Eslováquia" },
  { code: "+386", flag: "🇸🇮", country: "SI", label: "Eslovênia" },
  { code: "+252", flag: "🇸🇴", country: "SO", label: "Somália" },
  { code: "+27", flag: "🇿🇦", country: "ZA", label: "África do Sul" },
  { code: "+82", flag: "🇰🇷", country: "KR", label: "Coreia do Sul" },
  { code: "+34", flag: "🇪🇸", country: "ES", label: "Espanha" },
  { code: "+94", flag: "🇱🇰", country: "LK", label: "Sri Lanka" },
  { code: "+249", flag: "🇸🇩", country: "SD", label: "Sudão" },
  { code: "+597", flag: "🇸🇷", country: "SR", label: "Suriname" },
  { code: "+46", flag: "🇸🇪", country: "SE", label: "Suécia" },
  { code: "+41", flag: "🇨🇭", country: "CH", label: "Suíça" },
  { code: "+963", flag: "🇸🇾", country: "SY", label: "Síria" },
  { code: "+886", flag: "🇹🇼", country: "TW", label: "Taiwan" },
  { code: "+992", flag: "🇹🇯", country: "TJ", label: "Tajiquistão" },
  { code: "+255", flag: "🇹🇿", country: "TZ", label: "Tanzânia" },
  { code: "+66", flag: "🇹🇭", country: "TH", label: "Tailândia" },
  { code: "+228", flag: "🇹🇬", country: "TG", label: "Togo" },
  { code: "+216", flag: "🇹🇳", country: "TN", label: "Tunísia" },
  { code: "+90", flag: "🇹🇷", country: "TR", label: "Turquia" },
  { code: "+993", flag: "🇹🇲", country: "TM", label: "Turcomenistão" },
  { code: "+256", flag: "🇺🇬", country: "UG", label: "Uganda" },
  { code: "+380", flag: "🇺🇦", country: "UA", label: "Ucrânia" },
  { code: "+971", flag: "🇦🇪", country: "AE", label: "Emirados Árabes" },
  { code: "+44", flag: "🇬🇧", country: "GB", label: "Reino Unido" },
  { code: "+1", flag: "🇺🇸", country: "US", label: "Estados Unidos" },
  { code: "+598", flag: "🇺🇾", country: "UY", label: "Uruguai" },
  { code: "+998", flag: "🇺🇿", country: "UZ", label: "Uzbequistão" },
  { code: "+58", flag: "🇻🇪", country: "VE", label: "Venezuela" },
  { code: "+84", flag: "🇻🇳", country: "VN", label: "Vietnã" },
  { code: "+967", flag: "🇾🇪", country: "YE", label: "Iêmen" },
  { code: "+260", flag: "🇿🇲", country: "ZM", label: "Zâmbia" },
  { code: "+263", flag: "🇿🇼", country: "ZW", label: "Zimbábue" },
  { code: "+1", flag: "🇩🇴", country: "DO", label: "Rep. Dominicana" },
  { code: "+1", flag: "🇵🇷", country: "PR", label: "Porto Rico" },
  { code: "+1", flag: "🇹🇹", country: "TT", label: "Trinidad e Tobago" },
];

// Build country code → DDI mapping (prioritize specific countries for shared codes)
export const COUNTRY_TO_DDI: Record<string, string> = {};
COUNTRY_CODES.forEach((c) => { COUNTRY_TO_DDI[c.country] = c.code; });

// For the phone selector, deduplicate by using country code as unique key
// But since multiple countries share codes (e.g., +1), we use country as the value
export function findCountryByCode(countryCode: string): CountryCode | undefined {
  return COUNTRY_CODES.find((c) => c.country === countryCode);
}
