// All Stripe-supported currencies
// https://docs.stripe.com/currencies
const CURRENCY_CONFIG: Record<string, { symbol: string; locale: string; decimals: number }> = {
  aed: { symbol: "د.إ", locale: "ar-AE", decimals: 2 },
  afn: { symbol: "؋", locale: "fa-AF", decimals: 2 },
  all: { symbol: "L", locale: "sq-AL", decimals: 2 },
  amd: { symbol: "֏", locale: "hy-AM", decimals: 2 },
  ang: { symbol: "ƒ", locale: "nl-CW", decimals: 2 },
  aoa: { symbol: "Kz", locale: "pt-AO", decimals: 2 },
  ars: { symbol: "ARS", locale: "es-AR", decimals: 2 },
  aud: { symbol: "A$", locale: "en-AU", decimals: 2 },
  awg: { symbol: "ƒ", locale: "nl-AW", decimals: 2 },
  azn: { symbol: "₼", locale: "az-AZ", decimals: 2 },
  bam: { symbol: "KM", locale: "bs-BA", decimals: 2 },
  bbd: { symbol: "Bds$", locale: "en-BB", decimals: 2 },
  bdt: { symbol: "৳", locale: "bn-BD", decimals: 2 },
  bgn: { symbol: "лв", locale: "bg-BG", decimals: 2 },
  bif: { symbol: "FBu", locale: "fr-BI", decimals: 0 },
  bmd: { symbol: "BD$", locale: "en-BM", decimals: 2 },
  bnd: { symbol: "B$", locale: "ms-BN", decimals: 2 },
  bob: { symbol: "Bs.", locale: "es-BO", decimals: 2 },
  brl: { symbol: "R$", locale: "pt-BR", decimals: 2 },
  bsd: { symbol: "B$", locale: "en-BS", decimals: 2 },
  bwp: { symbol: "P", locale: "en-BW", decimals: 2 },
  bzd: { symbol: "BZ$", locale: "en-BZ", decimals: 2 },
  cad: { symbol: "CA$", locale: "en-CA", decimals: 2 },
  cdf: { symbol: "FC", locale: "fr-CD", decimals: 2 },
  chf: { symbol: "CHF", locale: "de-CH", decimals: 2 },
  clp: { symbol: "CLP", locale: "es-CL", decimals: 0 },
  cny: { symbol: "¥", locale: "zh-CN", decimals: 2 },
  cop: { symbol: "COP", locale: "es-CO", decimals: 2 },
  crc: { symbol: "₡", locale: "es-CR", decimals: 2 },
  cve: { symbol: "CVE", locale: "pt-CV", decimals: 2 },
  czk: { symbol: "Kč", locale: "cs-CZ", decimals: 2 },
  djf: { symbol: "Fdj", locale: "fr-DJ", decimals: 0 },
  dkk: { symbol: "kr", locale: "da-DK", decimals: 2 },
  dop: { symbol: "RD$", locale: "es-DO", decimals: 2 },
  dzd: { symbol: "د.ج", locale: "ar-DZ", decimals: 2 },
  egp: { symbol: "E£", locale: "ar-EG", decimals: 2 },
  etb: { symbol: "Br", locale: "am-ET", decimals: 2 },
  eur: { symbol: "€", locale: "de-DE", decimals: 2 },
  fjd: { symbol: "FJ$", locale: "en-FJ", decimals: 2 },
  fkp: { symbol: "FK£", locale: "en-FK", decimals: 2 },
  gbp: { symbol: "£", locale: "en-GB", decimals: 2 },
  gel: { symbol: "₾", locale: "ka-GE", decimals: 2 },
  gip: { symbol: "£", locale: "en-GI", decimals: 2 },
  gmd: { symbol: "D", locale: "en-GM", decimals: 2 },
  gnf: { symbol: "FG", locale: "fr-GN", decimals: 0 },
  gtq: { symbol: "Q", locale: "es-GT", decimals: 2 },
  gyd: { symbol: "GY$", locale: "en-GY", decimals: 2 },
  hkd: { symbol: "HK$", locale: "zh-HK", decimals: 2 },
  hnl: { symbol: "L", locale: "es-HN", decimals: 2 },
  htg: { symbol: "G", locale: "fr-HT", decimals: 2 },
  huf: { symbol: "Ft", locale: "hu-HU", decimals: 2 },
  idr: { symbol: "Rp", locale: "id-ID", decimals: 2 },
  ils: { symbol: "₪", locale: "he-IL", decimals: 2 },
  inr: { symbol: "₹", locale: "en-IN", decimals: 2 },
  isk: { symbol: "kr", locale: "is-IS", decimals: 2 },
  jmd: { symbol: "J$", locale: "en-JM", decimals: 2 },
  jpy: { symbol: "¥", locale: "ja-JP", decimals: 0 },
  kes: { symbol: "KSh", locale: "en-KE", decimals: 2 },
  kgs: { symbol: "сом", locale: "ky-KG", decimals: 2 },
  khr: { symbol: "៛", locale: "km-KH", decimals: 2 },
  kmf: { symbol: "CF", locale: "fr-KM", decimals: 0 },
  krw: { symbol: "₩", locale: "ko-KR", decimals: 0 },
  kyd: { symbol: "CI$", locale: "en-KY", decimals: 2 },
  kzt: { symbol: "₸", locale: "kk-KZ", decimals: 2 },
  lak: { symbol: "₭", locale: "lo-LA", decimals: 2 },
  lbp: { symbol: "L£", locale: "ar-LB", decimals: 2 },
  lkr: { symbol: "Rs", locale: "si-LK", decimals: 2 },
  lrd: { symbol: "L$", locale: "en-LR", decimals: 2 },
  lsl: { symbol: "L", locale: "en-LS", decimals: 2 },
  mad: { symbol: "د.م.", locale: "ar-MA", decimals: 2 },
  mdl: { symbol: "L", locale: "ro-MD", decimals: 2 },
  mga: { symbol: "Ar", locale: "mg-MG", decimals: 0 },
  mkd: { symbol: "ден", locale: "mk-MK", decimals: 2 },
  mmk: { symbol: "K", locale: "my-MM", decimals: 2 },
  mnt: { symbol: "₮", locale: "mn-MN", decimals: 2 },
  mop: { symbol: "MOP$", locale: "zh-MO", decimals: 2 },
  mur: { symbol: "₨", locale: "en-MU", decimals: 2 },
  mvr: { symbol: "Rf", locale: "dv-MV", decimals: 2 },
  mwk: { symbol: "MK", locale: "en-MW", decimals: 2 },
  mxn: { symbol: "MX$", locale: "es-MX", decimals: 2 },
  myr: { symbol: "RM", locale: "ms-MY", decimals: 2 },
  mzn: { symbol: "MTn", locale: "pt-MZ", decimals: 2 },
  nad: { symbol: "N$", locale: "en-NA", decimals: 2 },
  ngn: { symbol: "₦", locale: "en-NG", decimals: 2 },
  nio: { symbol: "C$", locale: "es-NI", decimals: 2 },
  nok: { symbol: "kr", locale: "nb-NO", decimals: 2 },
  npr: { symbol: "₨", locale: "ne-NP", decimals: 2 },
  nzd: { symbol: "NZ$", locale: "en-NZ", decimals: 2 },
  pab: { symbol: "B/.", locale: "es-PA", decimals: 2 },
  pen: { symbol: "S/", locale: "es-PE", decimals: 2 },
  pgk: { symbol: "K", locale: "en-PG", decimals: 2 },
  php: { symbol: "₱", locale: "en-PH", decimals: 2 },
  pkr: { symbol: "₨", locale: "ur-PK", decimals: 2 },
  pln: { symbol: "zł", locale: "pl-PL", decimals: 2 },
  pyg: { symbol: "₲", locale: "es-PY", decimals: 0 },
  qar: { symbol: "QR", locale: "ar-QA", decimals: 2 },
  ron: { symbol: "lei", locale: "ro-RO", decimals: 2 },
  rsd: { symbol: "din.", locale: "sr-RS", decimals: 2 },
  rub: { symbol: "₽", locale: "ru-RU", decimals: 2 },
  rwf: { symbol: "RF", locale: "rw-RW", decimals: 0 },
  sar: { symbol: "﷼", locale: "ar-SA", decimals: 2 },
  sbd: { symbol: "SI$", locale: "en-SB", decimals: 2 },
  scr: { symbol: "₨", locale: "en-SC", decimals: 2 },
  sek: { symbol: "kr", locale: "sv-SE", decimals: 2 },
  sgd: { symbol: "S$", locale: "en-SG", decimals: 2 },
  shp: { symbol: "£", locale: "en-SH", decimals: 2 },
  sle: { symbol: "Le", locale: "en-SL", decimals: 2 },
  sos: { symbol: "Sh", locale: "so-SO", decimals: 2 },
  srd: { symbol: "SRD", locale: "nl-SR", decimals: 2 },
  std: { symbol: "Db", locale: "pt-ST", decimals: 2 },
  szl: { symbol: "E", locale: "en-SZ", decimals: 2 },
  thb: { symbol: "฿", locale: "th-TH", decimals: 2 },
  tjs: { symbol: "SM", locale: "tg-TJ", decimals: 2 },
  top: { symbol: "T$", locale: "to-TO", decimals: 2 },
  try: { symbol: "₺", locale: "tr-TR", decimals: 2 },
  ttd: { symbol: "TT$", locale: "en-TT", decimals: 2 },
  twd: { symbol: "NT$", locale: "zh-TW", decimals: 2 },
  tzs: { symbol: "TSh", locale: "sw-TZ", decimals: 2 },
  uah: { symbol: "₴", locale: "uk-UA", decimals: 2 },
  ugx: { symbol: "USh", locale: "en-UG", decimals: 0 },
  usd: { symbol: "$", locale: "en-US", decimals: 2 },
  uyu: { symbol: "UYU", locale: "es-UY", decimals: 2 },
  uzs: { symbol: "сўм", locale: "uz-UZ", decimals: 2 },
  vnd: { symbol: "₫", locale: "vi-VN", decimals: 0 },
  vuv: { symbol: "VT", locale: "en-VU", decimals: 0 },
  wst: { symbol: "WS$", locale: "en-WS", decimals: 2 },
  xaf: { symbol: "FCFA", locale: "fr-CM", decimals: 0 },
  xcd: { symbol: "EC$", locale: "en-AG", decimals: 2 },
  xof: { symbol: "CFA", locale: "fr-SN", decimals: 0 },
  xpf: { symbol: "₣", locale: "fr-PF", decimals: 0 },
  yer: { symbol: "﷼", locale: "ar-YE", decimals: 2 },
  zar: { symbol: "R", locale: "en-ZA", decimals: 2 },
  zmw: { symbol: "ZK", locale: "en-ZM", decimals: 2 },
};

export const SUPPORTED_CURRENCIES = Object.keys(CURRENCY_CONFIG);

export function getCurrencyLabel(code: string): string {
  const labels: Record<string, string> = {
    aed: "AED – Dirham dos Emirados",
    afn: "AFN – Afghani Afegão",
    all: "ALL – Lek Albanês",
    amd: "AMD – Dram Armênio",
    ang: "ANG – Florim Antilhano",
    aoa: "AOA – Kwanza Angolano",
    ars: "ARS – Peso Argentino",
    aud: "AUD – Dólar Australiano",
    awg: "AWG – Florim de Aruba",
    azn: "AZN – Manat Azerbaijano",
    bam: "BAM – Marco Conversível (Bósnia)",
    bbd: "BBD – Dólar de Barbados",
    bdt: "BDT – Taka de Bangladesh",
    bgn: "BGN – Lev Búlgaro",
    bif: "BIF – Franco Burundiano",
    bmd: "BMD – Dólar das Bermudas",
    bnd: "BND – Dólar de Brunei",
    bob: "BOB – Boliviano",
    brl: "BRL – Real Brasileiro",
    bsd: "BSD – Dólar das Bahamas",
    bwp: "BWP – Pula de Botsuana",
    bzd: "BZD – Dólar de Belize",
    cad: "CAD – Dólar Canadense",
    cdf: "CDF – Franco Congolês",
    chf: "CHF – Franco Suíço",
    clp: "CLP – Peso Chileno",
    cny: "CNY – Yuan Chinês",
    cop: "COP – Peso Colombiano",
    crc: "CRC – Colón Costarriquenho",
    cve: "CVE – Escudo Cabo-Verdiano",
    czk: "CZK – Coroa Tcheca",
    djf: "DJF – Franco Djiboutiano",
    dkk: "DKK – Coroa Dinamarquesa",
    dop: "DOP – Peso Dominicano",
    dzd: "DZD – Dinar Argelino",
    egp: "EGP – Libra Egípcia",
    etb: "ETB – Birr Etíope",
    eur: "EUR – Euro",
    fjd: "FJD – Dólar de Fiji",
    fkp: "FKP – Libra das Malvinas",
    gbp: "GBP – Libra Esterlina",
    gel: "GEL – Lari Georgiano",
    gip: "GIP – Libra de Gibraltar",
    gmd: "GMD – Dalasi Gambiano",
    gnf: "GNF – Franco Guineano",
    gtq: "GTQ – Quetzal Guatemalteco",
    gyd: "GYD – Dólar da Guiana",
    hkd: "HKD – Dólar de Hong Kong",
    hnl: "HNL – Lempira Hondurenha",
    htg: "HTG – Gourde Haitiano",
    huf: "HUF – Forint Húngaro",
    idr: "IDR – Rúpia Indonésia",
    ils: "ILS – Shekel Israelense",
    inr: "INR – Rúpia Indiana",
    isk: "ISK – Coroa Islandesa",
    jmd: "JMD – Dólar Jamaicano",
    jpy: "JPY – Iene Japonês",
    kes: "KES – Xelim Queniano",
    kgs: "KGS – Som Quirguiz",
    khr: "KHR – Riel Cambojano",
    kmf: "KMF – Franco Comoriano",
    krw: "KRW – Won Sul-Coreano",
    kyd: "KYD – Dólar das Ilhas Cayman",
    kzt: "KZT – Tenge Cazaque",
    lak: "LAK – Kip Laosiano",
    lbp: "LBP – Libra Libanesa",
    lkr: "LKR – Rúpia do Sri Lanka",
    lrd: "LRD – Dólar Liberiano",
    lsl: "LSL – Loti do Lesoto",
    mad: "MAD – Dirham Marroquino",
    mdl: "MDL – Leu Moldavo",
    mga: "MGA – Ariary Malgaxe",
    mkd: "MKD – Denar Macedônio",
    mmk: "MMK – Kyat de Mianmar",
    mnt: "MNT – Tugrik Mongol",
    mop: "MOP – Pataca de Macau",
    mur: "MUR – Rúpia Mauriciana",
    mvr: "MVR – Rufiyaa Maldiva",
    mwk: "MWK – Kwacha Malauiano",
    mxn: "MXN – Peso Mexicano",
    myr: "MYR – Ringgit Malaio",
    mzn: "MZN – Metical Moçambicano",
    nad: "NAD – Dólar Namibiano",
    ngn: "NGN – Naira Nigeriana",
    nio: "NIO – Córdoba Nicaraguense",
    nok: "NOK – Coroa Norueguesa",
    npr: "NPR – Rúpia Nepalesa",
    nzd: "NZD – Dólar Neozelandês",
    pab: "PAB – Balboa Panamenho",
    pen: "PEN – Sol Peruano",
    pgk: "PGK – Kina de Papua Nova Guiné",
    php: "PHP – Peso Filipino",
    pkr: "PKR – Rúpia Paquistanesa",
    pln: "PLN – Zloty Polonês",
    pyg: "PYG – Guarani Paraguaio",
    qar: "QAR – Rial Catarense",
    ron: "RON – Leu Romeno",
    rsd: "RSD – Dinar Sérvio",
    rub: "RUB – Rublo Russo",
    rwf: "RWF – Franco Ruandês",
    sar: "SAR – Rial Saudita",
    sbd: "SBD – Dólar das Ilhas Salomão",
    scr: "SCR – Rúpia de Seicheles",
    sek: "SEK – Coroa Sueca",
    sgd: "SGD – Dólar de Singapura",
    shp: "SHP – Libra de Santa Helena",
    sle: "SLE – Leone de Serra Leoa",
    sos: "SOS – Xelim Somali",
    srd: "SRD – Dólar Surinamês",
    std: "STD – Dobra São-Tomense",
    szl: "SZL – Lilangeni Suazi",
    thb: "THB – Baht Tailandês",
    tjs: "TJS – Somoni Tajique",
    top: "TOP – Pa'anga Tonganesa",
    try: "TRY – Lira Turca",
    ttd: "TTD – Dólar de Trinidad e Tobago",
    twd: "TWD – Dólar Taiwanês",
    tzs: "TZS – Xelim Tanzaniano",
    uah: "UAH – Hryvnia Ucraniano",
    ugx: "UGX – Xelim Ugandense",
    usd: "USD – Dólar Americano",
    uyu: "UYU – Peso Uruguaio",
    uzs: "UZS – Som Uzbeque",
    vnd: "VND – Dong Vietnamita",
    vuv: "VUV – Vatu de Vanuatu",
    wst: "WST – Tala Samoano",
    xaf: "XAF – Franco CFA (Central)",
    xcd: "XCD – Dólar do Caribe Oriental",
    xof: "XOF – Franco CFA (Ocidental)",
    xpf: "XPF – Franco CFP",
    yer: "YER – Rial Iemenita",
    zar: "ZAR – Rand Sul-Africano",
    zmw: "ZMW – Kwacha Zambiano",
  };
  return labels[code] || code.toUpperCase();
}

// Currencies where Intl uses an ambiguous single-letter symbol (e.g. "R" for ZAR)
// and we prefer the ISO code instead for clarity
const USE_ISO_CODE: Record<string, boolean> = {
  zar: true,
  mzn: true,
};

export function formatCents(cents: number, currency = "eur"): string {
  // Normalize to lowercase so "EUR", "Eur", "eur" all resolve correctly
  const normalized = (currency || "eur").trim().toLowerCase();
  const config = CURRENCY_CONFIG[normalized] || CURRENCY_CONFIG.eur;
  const value = cents / Math.pow(10, config.decimals);
  const formatted = new Intl.NumberFormat(config.locale, {
    style: "currency",
    currency: normalized.toUpperCase(),
    minimumFractionDigits: config.decimals,
    maximumFractionDigits: config.decimals,
  }).format(value);

  if (USE_ISO_CODE[normalized]) {
    // Replace the native symbol with the ISO code (e.g. "R 1,00" → "ZAR 1,00")
    return formatted.replace(config.symbol, normalized.toUpperCase() + " ").replace(/\s+/g, " ").trim();
  }
  // Uppercase any alphabetic currency symbol/code (e.g. "kr" → "KR", "lei" → "LEI")
  return formatted.replace(/[a-zA-ZÀ-ÖØ-öø-ÿ]+/g, (m) => m.toUpperCase());
}

// Keep backward compat
export function formatCentsToBRL(cents: number): string {
  return formatCents(cents, "brl");
}

export function parsePriceToCents(value: string, currency = "eur"): number {
  const config = CURRENCY_CONFIG[currency] || CURRENCY_CONFIG.eur;
  const cleaned = value.replace(/[^\d.,]/g, "").replace(",", ".");
  return Math.round(parseFloat(cleaned) * Math.pow(10, config.decimals));
}

export function parseBRLToCents(value: string): number {
  return parsePriceToCents(value, "brl");
}

export function isZeroDecimalCurrency(currency: string): boolean {
  const config = CURRENCY_CONFIG[currency];
  return config ? config.decimals === 0 : false;
}

export function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
