project_id = "hqtxjvepadcsfcvvsiwx"

[functions.create-intent]
verify_jwt = false

[functions.sync-product]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.confirm-payment]
verify_jwt = false

[functions.offer-decision]
verify_jwt = false

[functions.generate-offer-url]
verify_jwt = false
